batch_size: 32
max_steps: 1500
log_every: 100
eval_every: 200
save_every: 500
grad_clip: 1.0

optimizer:
  lr: 3e-4
  betas: [0.9, 0.95]
  weight_decay: 0.1
  eps: 1e-8

scheduler:
  warmup_steps: 100
  cosine_steps: 1500

ckpt_dir: "ckpts"
resume_from: null